name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip AbsensiIndonesiaMaju.zip

      - name: Cari dan beri izin ke gradlew
        id: gradle_setup
        run: |
          export GRADLEW=$(find . -type f -name gradlew | head -n 1)
          if [ -z "$GRADLEW" ]; then
            echo "âŒ File gradlew tidak ditemukan"
            exit 1
          fi
          chmod +x "$GRADLEW"
          echo "GRADLEW=$GRADLEW" >> $GITHUB_ENV

      - name: Build APK
        run: |
          cd $(dirname $GRADLEW)
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Absensi-Indonesia-Maju-APK
          path: |
            **/app/build/outputs/apk/debug/*.apk
